### ISSUE TITLE
Question on Running CPU vs GPU

### ISSUE THREAD

**Issue by tkmontana** [agentmorris/MegaDetector#116]
Besides speed, are there performance differences when running megadetector on a CPU vs a GPU (or a lower quality GPU)? Particularly curious about differences in classifier confidence. Sorry if this is a dumb question :) TIA!!

**Comment by agentmorris** [comment]
Thanks for reaching out!  

<i><b>Short version...</b></i>

No, there are no differences, MegaDetector is MegaDetector.  Or, more specifically, for example, MDv5a is MDv5a.  If you run MDv5a on a CPU vs. the world's fastest GPU using the recommended instructions, you will get exactly the same results out to a zillion decimal places.

<i><b>Long and unnecessarily nuanced version...</b></i>

Really, this is way out into the weeds, so I wouldn't worry about most of this.  When in doubt, go with the short version above. :)  But I didn't want to promise that everyone always gets exactly the same results without qualifying things a bit.

There are several ways you can "run MDv5a" but end up with very slightly different results than someone else who also "runs MDv5a".  I stress these are very small differences, but they are just enough to be annoying if you literally want to compare the equality of confidence values and box coordinates:

- In order to run MegaDetector on M1/M2 Macs (i.e., Apple silicon), you have to use slightly different versions of some of MegaDetector's dependencies.  This happens behind the scenes if you use, for example, [EcoAssist](https://github.com/PetervanLunteren/EcoAssist), or if you run MegaDetector through the [MegaDetector Python package](https://pypi.org/project/megadetector/).  It works, but results will be ever-so-very-slightly different, like maybe out at the third decimal place.  Are those differences important?  Probably not.
- Some third-party packages convert the MegaDetector model file to another format, e.g. [CamTrap Detector](https://camtrap.net/detector) converts MegaDetector to ONNX, and [Animl](https://github.com/conservationtechlab/animl) converts MegaDetector to (IIRC) TensorFlow.  There are very sensible things to do, but they are opinionated transformations that will result in ever-so-very-slight differences.
- Lastly, if you follow the recommended MegaDetector installation instructions, you will be using a very specific version of the YOLOv5 repo, in which we've [changed literally one line](https://github.com/ecologize/yolov5/commit/a5b7d2b7554049ea71ef664c4a82bd9bfc9843c4).  That's because there is one step that runs on the CPU, and in the official YOLOv5 code, if that step takes too long, the code bails on it, which doesn't exactly make anything "wrong", but it can result in ever-so-very-slight differences when you run on a very slow CPU.  As long as you follow the recommended installation instructions, this is a non-issue.  But if you, e.g., use the Python package, or branch out on your own and use a newer version of the YOLOv5 code, you may get ever-so-very-slight differences when running in a very slow environment.

Hope that helps!

Always feel free to reach out here, or to email <a href="cameratraps@lila.science">cameratraps@lila.science</a> with questions.  Happy MegaDetect'ing!
