### ISSUE TITLE
Update get_lila_annotation_counts.py script to work with metatdata schema

### ISSUE THREAD

**Issue by nathanielrindlaub** [agentmorris/MegaDetector#124]
Hey @agentmorris, 

I was just poking around your LILA scripts and noticed a small bug in this [line](https://github.com/agentmorris/MegaDetector/blob/94f694167250dfeaa1e5e53976dd5697d9b78a1d/data_management/lila/get_lila_annotation_counts.py#L101) of the `get_lila_annotation_counts.py` script. 

It looks like the `image_base_url` key no longer exists in the dict returned by [`lila_read_metadata()`](https://github.com/agentmorris/MegaDetector/blob/94f694167250dfeaa1e5e53976dd5697d9b78a1d/data_management/lila/lila_common.py#L118), and instead the image base url headers now follow this pattern: `image_base_url_<cloud_provider>`. 

I fixed this by adding `preffered_cloud = 'gcp'` to the top of the file and modifying that line to:

```python
    base_url = metadata_table[ds_name]['image_base_url_' + preferred_cloud]
```

Happy to open a PR for that change if you'd like.

**Comment by agentmorris** [comment]
Wow, you're fast!  That change to the metadata just happened this weekend.  Yes, that's the same change I would have made, please open a PR.  Thanks!

**Comment by agentmorris** [comment]
I'm happy to give you write access because I know you :), but... I think standard practice is for you to fork the repo, make your changes there, then create a PR from your repo into this repo.  E.g. [this recent PR](https://github.com/agentmorris/MegaDetector/pull/122) was submitted by a contributor who does not have write access to the repo, and that went smoothly.

GitHub's [documentation on this process](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) is clear and helpful, except for the confusing part where it says that you need write access; I'm 99.999% sure they mean that you need write access to the _source_ repo, which in this case would be your fork.

Try that and let me know if you hit any snags?  Thanks!

**Comment by nathanielrindlaub** [comment]
Ah! I rarely contribute to external repos so had no idea you could create a PR from a forked project. Thanks I think that got me sorted.

**Comment by agentmorris** [comment]
Merged, closing this issue.  Thanks for finding this!
